- name: Enviar alerta pro Discord
  if: always()
  run: |
    curl -H "Content-Type: application/json" \
    -d "{\"content\": \"🚨 Status: ${{ job.status }}\"}" \
    ${{ secrets.DISCORDWEBHOOK }}