name: CI com alerta Discord

on:
  push:
    branches: [ "master, main, develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORDWEBHOOK }}
        with:
          args: '🚀 Deploy realizado!'
          #teste teste