name: Teste Discord

on:
  push:
    branches: [ "master", "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"🔥 Teste funcionando\"}" \
          ${{ secrets.DISCORDWEBHOOK }}